### ISSUE TITLE
Basic Rules

### ISSUE THREAD

**Issue by MohammadAlHabil** [GSG-G11/ImageSearch#4]
### Color
```html
<html lang="en" data-theme="light">
```
```CSS 
:root{
--white: #ffffff;
--main: #B12025;
--active-background: #111317;
--sec-background: #171A1F;
--background: #0A0B0D;
--title: #E1E6F0;
--sub-title: #8B919C;
--placeholder: #B8BFCC;
--border: #1B1F26;
--between-border: #242933;
--icon: #F7FAFC;
}

[data-theme="dark"] {
--black: #000000;
--main: #B12025;
--active-background: #FFFFFF;
--sec-background: #FAFAFA;
--background: #FFFFFF;
--title: #B8BFCC;
--sub-title: #8B919C;
--placeholder: #B8BFCC;
--border: #E1E6F0;
--between-border: #E1E6F0;
--icon: #F7FAFC;
}
```
### Font
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&family=Readex+Pro:wght@200;300;400;500;600;700&family=Yeseva+One&display=swap" rel="stylesheet">
```
- Use this font in CSS 

> 
```CSS 
font-family: 'Readex Pro', sans-serif;
```
